create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    customer_name text not null,
    phone text not null,
    category text not null,
    location text,
    items jsonb not null,
    total numeric not null,
    created_at timestamptz not null default now()
);

alter table public.orders add column if not exists customer_name text;
alter table public.orders add column if not exists phone text;
alter table public.orders add column if not exists category text;
alter table public.orders add column if not exists location text;
alter table public.orders add column if not exists items jsonb;
alter table public.orders add column if not exists total numeric;
alter table public.orders add column if not exists created_at timestamptz default now();

alter table public.orders enable row level security;

drop policy if exists "Allow anonymous order inserts" on public.orders;
create policy "Allow anonymous order inserts"
on public.orders
for insert
to anon
with check (true);

drop policy if exists "Allow anonymous order reads" on public.orders;
create policy "Allow anonymous order reads"
on public.orders
for select
to anon
using (true);
